blank_issues_enabled: false
contact_links:
  - name: â“ Ask a question
    url: https://github.com/wakatime/wakatime-cli/discussions/new?category=q-a
    about: Ask and discuss questions with other WakaTime community members

  - name: ğŸ’¬ Slack channel
    url: https://wakaslack.herokuapp.com
    about: Please ask and answer questions here
