name: "Tests"

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: lekterable/branchlint-action@1.2.0
        with:
          allowed: |
            /^(.+:)?bugfix/.+/i
            /^(.+:)?docs?/.+/i
            /^(.+:)?feature/.+/i
            /^(.+:)?hotfix/.+/i
            /^(.+:)?major/.+/i
            /^(.+:)?misc/.+/i
            /^(.+:)?develop$/i
